#!/usr/bin/perl -w

use strict;
use FindBin qw($Bin);
use lib $Bin;
use ParseCH qw(:ALL);

parser(@ARGV);
my($linkto, $node);

print("<!DOCTYPE TREE PUBLIC \"-//Comp_Hist//DTD CHML 1.0//EN\" \"http://comp-hist.sourceforge.net/comp-hist.dtd\">\n\n");

print("<tree>\n");

foreach $node (sort keys %Name){
  print("<node>\n");
  print("\t<id>$node</id>\n");
  print("\t<name>$Name{$node}</name>\n");
  print("\t<date Year=\"$Year{$node}\"") if defined $Year{$node};
  print(" month=\"$Month{$node}\"") if defined $Month{$node}; 
  print(" day=\"$Day{$node}\"") if defined $Day{$node};
  print(" />\n") if defined $Year{$node};
  print("\t<type types=\"$Type{$node}\" />\n") if defined $Type{$node};
  print("\t<status status=\"$Status{$node}\" />\n") if defined $Status{$node};
  print("\t<reference>$Reference{$node} </reference>\n") if defined $Reference{$node};
  print("\t<info>$Info{$node} </info>\n") if defined $Info{$node};
  foreach $linkto (keys %{$Linkto{$node}}){
    print("\t<link linktype=\"$Linkto{$node}{$linkto}\"><id>$linkto</id></link>");
  }
  print("</node>\n\n");
}

print("</tree>\n");

