#!/usr/bin/perl -w

use strict;
no strict 'refs';
use FindBin qw($Bin);
use lib $Bin;
use ParseCH qw(:ALL);
use ParseCH::DirGraph qw(:ALL);

parser(@ARGV);

#variable setup
my $d;
my($Minyear, $Maxyear) = dominmaxYear(\%Year);
my %Linkcolor = setlinkcolor(\%Linkto);
my %Date = dopos("dot", 1, \%Year, \%Month);
my %Color = setcolor(\%Type);
my %Shape = setshape(\%Status);

#Print a dot header out
print("digraph comphist {\nratio=auto; page=\"8.25,11.65\";\n");
print("node [shape=plaintext,fontsize=24];\n");
print("ranksep=0.1; nodesep=0.1; center=true;\n\n");

#do a year timeline
print("{ edge [style=bold];\n");
for my $i ($Minyear .. $Maxyear) {
  print("\t$i->\n");
}
print("\tfuture;\n}\n\n");

#Print node rankings
foreach my $Month (sort keys %Date){
  print("{ rank=same; ");
  foreach my $node (keys %{$Date{$Month}}){
    print("\"$node\"; ");
  }
  print(" }\n");
}
print("\n");


#lock the invisible years in place
for my $i ($Minyear .. $Maxyear){
  print("{ edge [style=invis]\n");
  for my $j (0 .. 12){
    $d="$i.$j";
    print("\t$d [style=invis,height=0.1,width=0.2,fontsize=2];\n")
      if defined $Date{$d}{$d};
  }
  for my $j (0 .. 12){
    $d=sprintf("$i.%02d", $j);
    print("\t$d->\n")
      if defined $Date{$d}{$d};
  }
  printf("\t%d.00;\n", $i+1);
  print("}\n");
}
printf("{ %d.00 [style=invis,height=0.1,width=0.2,fontsize=2]; }\n\n", $Maxyear+1);

#Write up the edges
foreach my $node (keys %Linkto){
  foreach my $linkto (keys %{$Linkto{$node}}){
    print("\"$linkto\" -> \"$node\" [color=$Linkcolor{$node}{$linkto}];\n");
  }
}
print("\n");

#Write the node info
foreach my $node (keys %Name){
  print("\"$node\" [label=\"$Name{$node}\"");
  print(",color=$Color{$node}") if defined $Color{$node};
  print(",shape=$Shape{$node}") if defined $Shape{$node};
  print("]\n");
}

#Close the dot file
print("}\n");
