#!/usr/bin/perl -wP

#include[parse.h]

print("digraph unixhist {\nratio=auto; page=\"8.25,11.65\";\n");
print("node [shape=plaintext,fontsize=24];\n");
print("ranksep=0.1; nodesep=0.1; center=true;\n");

# Draw the visible years
print("{ edge [style=bold];\n");
for ($i=$minyear; $i<=$maxyear; $i++) {
    $d= "$i.00"; $Date{$d}{$d}=$d; $Name{$d}=$d;
    $Date{$d}{$i}=$i; $Name{$i}=$i;
    print("  $i ->\n");
}
print("  future;\n}\n");
print("{ rank=max; future }\n");

foreach $i (sort(keys(%Date))) {
    print("{ rank=same; ");
    foreach $j (keys(%{ $Date{$i} })) {
        print("\"$Name{$j}\"; ");
    }
    print("}\n");
}

# Do the invisible years
for ($i=$minyear; $i<=$maxyear; $i++) { 
    print("{ edge [style=invis];\n");
    for ($j=0; $j<=12; $j++) {
        $d= sprintf("%d.%02d", $i,$j);
        if (!defined($Date{$d}{$d})) { next; }
        print("    $d [style=invis,height=0.1,width=0.1,fontsize=2];\n");
    }
    for ($j=0; $j<=12; $j++) {
        $d= sprintf("%d.%02d", $i,$j);
        if (!defined($Date{$d}{$d})) { next; }
        print("    $d ->\n");
    }
    printf("    %d.00;\n}\n",$i+1);
}
$j=$maxyear+1; $j .= ".00";
print("{ $j [style=invis,height=0.1,width=0.1,fontsize=2]; }\n");

for ($i=0; $i<$linkcnt; $i++) {
    if (!defined($Name{$From[$i]})) {
        print(STDERR "Warning: node $From[$i] doesn't exist\n"); next;
    }
    print("\"$Name{$From[$i]}\" -> \"$Name{$To[$i]}\" ");
    if ($Link[$i] eq "succ") { print("[weight=10,style=bold]"); }
    if ($Link[$i] eq "code") { print("[weight=5]"); }
    if ($Link[$i] eq "idea") { print("[weight=2,style=dotted]"); }
    print(";\n");
}
print("}\n");









