#!/usr/bin/perl -w 

#Togp, our third parser

$linkcnt = 0;

while(<>){
    if(/^(\S+)/){ $node = $1; }
    if(/.*Name: (.*)/){ $name{$node} = $1; }
    if(/.*Aka (\S+)/){ $from[$linkcnt] = $1; $to[$linkcnt] = $node; }
    if(/.*Successor to (\S+)/){ $from[$linkcnt] = $1; $to[$linkcnt] = $node; }
    if(/.*Code taken from (\S+)/){ $from[$linkcnt] = $1; $to[$linkcnt] = $node; }
    if(/.*Influenced by (\S+)/){ $from[$linkcnt] = $1; $to[$linkcnt] = $node; }
    if(/.*Runs on (\S+)/){ $from[$linkcnt] = $1; $to[$linkcnt] = $node; }
    if(/.*Made by (\S+)/){ $from[$linkcnt] = $1; $to[$linkcnt] = $node; }
}

foreach $node (keys %name){
    print("\"$name{$node}\" node\n");
}

foreach $linkcnt (@to){
    $from = $from[$linkcnt];
    $to = $to[$linkcnt];
    if(!defined $name{$from}){ print(STDERR "$name{$from} doesnt exist\n"); }
    else{
	print("\:$name{$from}\" \"$name{$to}\" edge\n");
    }
}




