#!/usr/bin/perl -w

#Tovcg, take 3

%files = ();
@files = @ARGV;
$minyear = 3000000;

print("graph: {\n\ttitle: \"The Computer Family Tree\"\n\n");

foreach $file (@files){
    parse($file);
}

foreach $file (@files){
    dopos($file);
    graph($file);
}

print("\n}\n");

sub parse{
    my $file = $_[0];
    open FILE, $file;
    while(<FILE>){
	s/\#.*//;
	if(/^(\S+)/){ $node = $1; push( @{$files{$file}}, $1 ); next; }
	if(/.*Name: (.*)/){ $name{$node} = $1; next; }
	if(/.*Date.*(\d\d\d\d)-(\d\d)-\d\d/){$year{$node} = $1; $month{$node} =  $2; goto dodate;}
	if(/.*Date.*(\d\d\d\d)-(\d\d)/){$year{$node} = $1; $month{$node} = $2; goto dodate;}
	if(/.*Date.*(\d\d\d\d)/){ $year{$node} = $1; goto dodate; }
	if(/.*Founded.*(\d\d\d\d)-(\d\d)-\d\d/){$year{$node} = $1; $month{$node} =  $2; goto dodate;}
	if(/.*Founded.*(\d\d\d\d)-(\d\d)/){$year{$node} = $1; $month{$node} = $2; goto dodate;}
	if(/.*Founded.*(\d\d\d\d)/){
	    $year{$node} = $1; goto dodate;
	  dodate:
	    if($year{$node} < $minyear){ $minyear = $year{$node}; }
	}

	if(/.*Type: hardware/i){ $color{$node} = "color: blue"; }
	if(/.*Type: OS/i){ $color{$node} = "color: red"; }
	if(/.*Type: language/i){ $color{$node} = "color: green"; }
	if(/.*Type: standard/i){ $color{$node} = "color: yellow"; }
	if(/.*Type: other/i){ $color{$node} = "color: magenta"; } #You don't know about this line. Go away.
	if(/.*Type: company/i){ $color{$node} = "color: cyan"; }
	if(/.*Type: announcement/i){$color{$node} = "color: gold"; }

	if(/.*Status: released/i){ $shape{$node} = "shape: box"; }
	if(/.*Status: internal/i){ $shape{$node} = "shape: triangle"; } 
	if(/.*Status: continual evolution/i){ $shape{$node} = "shape: ellipse"; }
	if(/.*Status: prototype/i){ $shape{$node} = "shape: rhomb"; }
	if(/.*Status: research/i){ $shape{$node} = "shape: triangle"; }

	if(/.*Aka (\S+)/) {
	    print("\tedge: { sourcename: \"$1\" targetname: \"$node\" thickness: 8 arrowsize: 40 backarrowsize: 400 }\n");
	}
	if (/.*Successor to (\S+)/) {
	    print("\tedge: { sourcename: \"$1\" targetname: \"$node\" thickness: 4 arrowsize: 20 }\n");
	}
	if (/.*Code taken from (\S+)/) {
	    print("\tedge: { sourcename: \"$1\" targetname: \"$node\" }\n");
	}
	if (/.*Influenced by (\S+)/) {
	    print("\tedge: { sourcename: \"$1\" targetname: \"$node\" linestyle: dashed }\n");
	}
	if(/.*Runs on (\S+)/){
	    print("\tedge: { sourcename: \"$1\" targetname: \"$node\" thickness: 8 linestyle: dashed }\n");
	}
	if(/.*Ran on (\S+)/){
	    print("\tedge: { sourcename: \"$1\" targetname: \"$node\" thickness: 8 linestyle: dashed }\n");
	}
	if(/.*Written in (\S+)/){
	     print("\tedge: { sourcename: \"$1\" targetname: \"$node\" thickness: 6 linestyle: dashed }\n");
	 }
    }
}

sub dopos{
    my $file = $_[0];
    foreach $node (@{$files{$file}}){
	if(!defined $month{$node}){
	    $year = $year{$node} - $minyear;
	    $vpos{$node} = $year * 12;
	}
	else{
	    $year = $year{$node} - $minyear;
	    $vpos{$node} = $year * 12 + $month{$node};
	}
    }
   
sub graph{
    my $file = $_[0];
    print("\tgraph: {\n");
    print("\t\ttitle: \"Information in $file\"\n\t\tcolor: khaki\n\n");
    foreach $node (@{$files{$file}}){
	if(!defined $vpos{$node}){
	    print("\t\tnode: { title: \"$node\" label: \"$name{$node}\" $color{$node} $shape{$node} }\n");
	}
	else{
	    print("\t\tnode: { title: \"$node\" label: \"$name{$node}\" vertical_order: $vpos{$node} $color{$node} $shape{$node} }\n");
	}
    }
    print("\n}\n");
}

}

