#!/usr/bin/perl -w

#Tovcg, take 2

print("graph: {\ntitle: \"The Computer Family Tree\"\n\n");
while(<>){
    if(/.*\#/){ next; }
    if(/^(\S+)/){ $node = $1; next; }
    if(/.*Name: (.*)/){ $name{$node} = $1; next; }
    if(/.*Date.*(\d\d\d\d)-(\d\d)-\d\d/){$vpos{$node} = $1 * 12 + $2 - 1200;}
    if(/.*Date.*(\d\d\d\d)-(\d\d)/){$vpos{$node} = $1 * 12 + $2 - 1200;}
    if(/.*Date.*(\d\d\d\d)/){ $vpos{$node} = $1 * 12 - 1200; }
    if(/.*Type: hardware/){ $color{$node} = "color: blue"; }
    if(/.*Type: [OS|os]/){ $color{$node} = "color: red"; }
    if(/.*Type: language/){ $color{$node} = "color: green"; }
    if(/.*Type: standard/){ $color{$node} = "color: yellow"; }
    if(/.*Type: other/){ $color{$node} = "color: magenta"; } #You don't know about this line. Go away.

    if(/.*Aka (\S+)/) {
        print("edge: { sourcename: \"$1\" targetname: \"$node\" thickness: 8 arrowsize: 40 backarrowsize: 400 }\n");
    }
    if (/.*Successor to (\S+)/) {
        print("edge: { sourcename: \"$1\" targetname: \"$node\" thickness: 4 arrowsize: 20 }\n");
    }
    if (/.*Code taken from (\S+)/) {
        print("edge: { sourcename: \"$1\" targetname: \"$node\" }\n");
    }
    if (/.*Influenced by (\S+)/) {
        print("edge: { sourcename: \"$1\" targetname: \"$node\" linestyle: dashed }\n");
    }
    if(/.*[Runs|Ran] on (\S+)/){
	print("edge: { sourcename: \"$1\" targetname: \"$node\" thickness: 8 linestyle: dashed }\n");
    }
}

foreach $node (keys(%name)){
    if(!defined $vpos{$node}){
	print("node: { title: \"$node\" label: \"$name{$node}\" $color{$node} }\n");
    }
    else{
	print("node: { title: \"$node\" label: \"$name{$node}\" vertical_order: $vpos{$node} $color{$node} }\n");
    }
}
print("\n}\n");





