#!/usr/bin/perl -w

#Toxml, take 2

%files = ();
@files = @ARGV;
$name = '';
@linkfrom = '';
@linkto = '';
@linkweight = '';
%type = ();
%year = ();
%month = ();
%day = ();

foreach $file (@files){
    parse($file);
}

&xml;

sub parse{
    my $file = $_[0];
    open FILE, $file;
    while(<FILE>){
	s/\#.*//;
	if(/^(\S+)/){ $node = $1; push( @{$files{$file}}, $1 ); next; }
	if(/^\bName: (.*)/){ $name{$node} = $1; }
	if(/^\bDate.*(\d\d\d\d)-?(\d\d)?-?(\d\d)?/){ $year{$node} = $1; $month{$node} =  $2; $day{$node} = $3; }

	if(/^\bType: ([hardware|os|language|standard|other|company|announcement])/i){ $type{$node} = $1; }

	if(/^\bReference: (.*)/){ $reference{$node} = $1; }
  
	if(/^\bInfo: (.*)/){ $info{$node} = $1; }

	if(/^\bStatus: ([released|internal|prototype|research])/i){ $status{$node} = $1; }
	if(/^\bStatus: continual evolution/i){ $status{$node} = "contev"; }

	if(/^\bAka (\S+)/) { &linkup($node, $1, "aka"); }
	if(/^\bSuccessor to (\S+)/) { &linkup($node, $1, "successor"); }
	if(/^\bCode taken from (\S+)/) { &linkup($node, $1, "codetaken"); }
	if(/^\bInfluenced by (\S+)/) { &linkup($node, $1, "influenced"); }
	if(/^\bRuns on (\S+)/){ &linkup($node, $1, "runson"); }
	if(/^\bRan on (\S+)/){ &linkup($node, $1, "ranon"); }
	if(/^\bWritten in (\S+)/){ &linkup($node, $1, "writtenin"); }
    }
}

sub linkup{
    push(@{$linkto{$_[0]}}, $_[1]);
    push(@{$linkweight{$_[0]}}, $_[2]);
}

sub xml{
    print("<!DOCTYPE TREE PUBLIC \"\" \"http://comp-hist.sourceforge.net/comp-hist.dtd\"\n\n");

    print("<tree>\n");

    foreach $node (sort keys %name){
	print("<node>\n");
	print("\t<id>$node</id>\n");
	print("\t<name>$name{$node}</name>\n");
	print("\t<date year=\"$year{$node}\" month=\"$month{$node}\" day=\"$day{$node}\" />\n");
	print("\t<type types=\"$type{$node}\" />\n");
	print("\t<status status=\"$status{$node}\" />\n") if defined $status{$node};
	print("\t<reference>$reference{$node} </reference>\n");
	print("\t<info>$info{$node} </info>\n");
	for( $i=0; $i <= $#{$linkfrom{$node}}; $i++ ) {
	    print("\t<link linktype=\"${$linkweight{$node}}[$i]\"><id>${$linkfrom{$node}}[$i]</link>\n");
	}
	print("</node>\n");
    }

    print("</tree>\n");

}
