/* Automatically generated by po2tbl.sed from browser.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Computer History Browser", 2},
  {"Couldn't find pixmap file: %s", 3},
  {"Error loading pixmap file: %s", 4},
};

int _msg_tbl_length = 4;
